{
    "name": "Catalog",
    "summary": """Catalog of modules""",
    "description": """Catalog of modules""",
    "author": "Aurelien ROY",
    "website": "https://odoo.com",
    "category": "Productivity",
    "version": "17.0.1.0.0",
    "depends": [
        "base",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_config_parameter_data.xml",
        "views/menu.xml",
        "views/catalog_module.xml",
        "views/catalog_entry.xml",
        "views/catalog_author.xml",
        "views/catalog_repository.xml",
        "views/catalog_organization.xml",
        "views/catalog_branch.xml",
        "views/catalog_version.xml",
        "views/catalog_selection.xml",
        "wizard/add_to_selection.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3",
}
